export const AppleTheme = {
    background: '#F5F5F7',
    card: '#FFFFFF',
    text: '#1D1D1F',
    secondaryText: '#6E6E73',
    tertiaryText: '#8E8E93',
    separator: '#E5E5EA',
    accent: '#34C759',
    accentSoft: '#EAF8EF',
    accentText: '#248A3D',
    warning: '#FF9F0A',
    warningSoft: '#FFF4E0',
    warningText: '#A45B00',
    danger: '#FF453A',
    dangerSoft: '#FFEDEC',
    darkButton: '#1D1D1F',
    disabled: '#C7C7CC',
    input: '#FFFFFF',
    inputBorder: '#E5E5EA',
    shadow: {
        shadowColor: '#000',
        shadowOpacity: 0.08,
        shadowRadius: 20,
        shadowOffset: { width: 0, height: 10 },
        elevation: 3,
    },
};
